services:
  - type: web
    name: uber-auth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: sFksMuO06Q_g6XGayHtixwegmCAPjBl4
        sync: false
      - key: _njo4RLJS0E2jNU9ImLzlsBMirjTrJH8FNOqqXS_
        sync: false
      - key: https://uberha.onrender.com/callback
        sync: false
