services:
  - type: web
    name: uber-auth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: UBER_CLIENT_ID
      - key: UBER_CLIENT_SECRET
      - key: UBER_REDIRECT_URI
        value: https://uberha.onrender.com/callback
